name: publish-butler-sdk
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: cachix/install-nix-action@v13
      - run: | 
          nix-shell && npm i && npm run production
