name: publish-butler-sdk
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: setup-gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: '${{ secrets.PROJECT_ID }}'
          service_account_key: '${{ secrets.SA_KEY }}'
          export_default_credentials: true

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: cachix/install-nix-action@v13
      - run: | 
          npm i && npm run production
      - id: sdk-upload
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: ./public/butler.js
          destination: kimchee-public/
          service_account_key: '${{ secrets.SA_KEY }}'

